# Generated by Django 4.2.1 on 2023-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0002_rename_shpo_name_shop_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data ordered'),
        ),
    ]
